// Generates config.js (loaded by both popup.js and service-worker.js as an
// ES module) from an .env file, so the API URL is a fixed value baked in at
// build time rather than something typed into the popup. Deliberately
// dependency-free — this extension otherwise has no build tooling at all.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const dir = path.dirname(fileURLToPath(import.meta.url))
const envFile = process.argv[2]
if (!envFile) {
  console.error('Usage: node build-config.mjs <path-to-env-file>')
  process.exit(1)
}

const envPath = path.join(dir, envFile)
const parsed = Object.fromEntries(
  readFileSync(envPath, 'utf8')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .map((line) => {
      const eq = line.indexOf('=')
      return [line.slice(0, eq), line.slice(eq + 1)]
    }),
)

if (!parsed.API_URL) {
  console.error(`API_URL missing from ${envFile}`)
  process.exit(1)
}

writeFileSync(
  path.join(dir, 'config.js'),
  `// Generated by build-config.mjs from ${envFile} — do not edit directly.\nexport const API_URL = ${JSON.stringify(parsed.API_URL)}\n`,
)
console.log(`Wrote config.js with API_URL=${parsed.API_URL} (from ${envFile})`)
