version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    target-branch: "development"
    schedule:
      interval: "weekly"
    groups:
      backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "development"
    schedule:
      interval: "weekly"
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/backend"
    target-branch: "development"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/frontend"
    target-branch: "development"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
