"""Reusing recent AI responses instead of asking again (issue #139).

A local model on a laptop takes seconds per generation. Asking it the same
question twice in a minute is the difference between a feature that feels
instant and one nobody waits for.

Three rules decide what this is allowed to reuse, and each is a way a cache
turns into a source of wrong answers.

**The key includes the model and the provider.** A response generated by
`llama3.2` is not an answer from `mistral`, and serving one for the other would
make the model setting look broken in a way nobody could reproduce — the wrong
answer arrives only when a stale entry happens to exist.

**Entries are per user.** Prompts carry the learner's own vocabulary and
context. A shared cache would hand one person's material to another on a key
collision, and "it was only a definition" is not a defence anyone wants to
make.

**Failures are never cached.** A model that was unreachable a minute ago may be
running now, and caching the failure would keep a working system broken for the
length of the TTL.

Pure and in-process: a dict with bounds. Deliberately not Redis — this is a
latency optimisation for repeated questions in one sitting, and a cache that
needs its own service to be deployed is a cache most people will not have.
"""
from __future__ import annotations

import hashlib
import json
from collections import OrderedDict
from dataclasses import dataclass
from datetime import datetime, timedelta

# How long an entry stays usable. Short, because a model's answer is not a fact
# — it is one sample from a generator, and holding it for hours would make the
# product feel frozen to anyone trying to get a better suggestion by asking
# again.
DEFAULT_TTL = timedelta(minutes=15)

# Entries kept before the least recently used is dropped. Bounded because this
# lives in the process: an unbounded cache in a long-running server is a memory
# leak with a friendly name.
DEFAULT_MAX_ENTRIES = 500


@dataclass(frozen=True)
class CacheKey:
    """Everything that must match for a response to be reusable."""

    user_id: int
    provider: str
    model: str
    operation: str
    payload_digest: str

    @staticmethod
    def build(user_id: int, provider: str, model: str, operation: str, payload: dict) -> "CacheKey":
        # Sorted and separator-normalised so two logically identical payloads
        # produce one key regardless of how the caller happened to build the
        # dict. Without that the cache would miss constantly and quietly do
        # nothing.
        encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
        digest = hashlib.sha256(encoded.encode("utf-8")).hexdigest()
        return CacheKey(
            user_id=user_id,
            provider=provider,
            model=model,
            operation=operation,
            payload_digest=digest,
        )


@dataclass
class _Entry:
    value: object
    expires_at: datetime


class AIResponseCache:
    """Bounded, expiring, per-user cache of model responses."""

    def __init__(
        self, ttl: timedelta = DEFAULT_TTL, max_entries: int = DEFAULT_MAX_ENTRIES
    ) -> None:
        self.ttl = ttl
        self.max_entries = max_entries
        self._entries: OrderedDict[CacheKey, _Entry] = OrderedDict()
        self.hits = 0
        self.misses = 0

    def get(self, key: CacheKey, now: datetime) -> object | None:
        entry = self._entries.get(key)
        if entry is None:
            self.misses += 1
            return None
        if entry.expires_at <= now:
            # Dropped on read rather than swept on a timer. A background sweep
            # would be a second thing to get wrong for no benefit: an expired
            # entry costs nothing until someone asks for it.
            del self._entries[key]
            self.misses += 1
            return None
        self._entries.move_to_end(key)
        self.hits += 1
        return entry.value

    def put(self, key: CacheKey, value: object, now: datetime) -> None:
        """Store a response. Refuses to store nothing.

        An empty or None result is not an answer worth repeating, and caching
        it would keep serving that emptiness for the whole TTL.
        """
        if value is None or value == "" or value == [] or value == {}:
            return
        self._entries[key] = _Entry(value=value, expires_at=now + self.ttl)
        self._entries.move_to_end(key)
        while len(self._entries) > self.max_entries:
            self._entries.popitem(last=False)

    def invalidate_user(self, user_id: int) -> int:
        """Drop everything belonging to one learner.

        Needed when their vocabulary changes enough that old suggestions are
        about a deck that no longer exists, and when an account is deleted —
        data removal that left a cache holding the same content would not be
        removal.
        """
        doomed = [key for key in self._entries if key.user_id == user_id]
        for key in doomed:
            del self._entries[key]
        return len(doomed)

    def invalidate_model(self, provider: str, model: str) -> int:
        """Drop everything from one model.

        Called when the AI settings change. Entries would expire on their own,
        but an administrator who switches model and immediately tests it should
        see the new model's output, not the old one's for another quarter hour.
        """
        doomed = [
            key for key in self._entries if key.provider == provider and key.model == model
        ]
        for key in doomed:
            del self._entries[key]
        return len(doomed)

    def clear(self) -> None:
        self._entries.clear()

    def __len__(self) -> int:
        return len(self._entries)
