"""Repository interfaces (ports in the hexagonal-architecture sense).

Application use cases depend on these Protocols, never on concrete
SQLAlchemy classes (Dependency Inversion Principle). Concrete
implementations live in app.infrastructure.repositories and are wired up
in app.api.deps.

Python's structural typing.Protocol is used instead of ABCs so that
implementations don't need to inherit from anything domain-related —
infrastructure stays free to use plain SQLAlchemy-backed classes.
"""
from __future__ import annotations

from datetime import datetime
from typing import Protocol

from app.domain.entities import (
    Group,
    MnemonicNote,
    RecallSettings,
    Reminder,
    ReviewSession,
    Room,
    User,
    Word,
)


class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def add(self, user: User) -> User: ...
    def update(self, user: User) -> User: ...
    def delete(self, user_id: int) -> None: ...
    def list_all(self, search: str | None, limit: int, offset: int) -> list[User]: ...
    def count(self) -> int: ...
    def count_registered_since(self, since: datetime) -> int: ...


class GroupRepository(Protocol):
    def get_by_id(self, group_id: int) -> Group | None: ...
    def list_by_owner(self, owner_id: int) -> list[Group]: ...
    def add(self, group: Group) -> Group: ...
    def update(self, group: Group) -> Group: ...
    def delete(self, group_id: int) -> None: ...


class WordRepository(Protocol):
    def get_by_id(self, word_id: int) -> Word | None: ...
    def list_by_group(self, group_id: int) -> list[Word]: ...
    def list_due_for_user(self, user_id: int, limit: int, group_id: int | None = None) -> list[Word]: ...
    def add(self, word: Word) -> Word: ...
    def update(self, word: Word) -> Word: ...
    def delete(self, word_id: int) -> None: ...
    def count_by_group(self, group_id: int) -> int: ...
    def count_mastered_by_group(self, group_id: int) -> int: ...
    def distinct_languages_for_user(self, user_id: int) -> int: ...
    def total_learned_for_owner(self, owner_id: int) -> int: ...
    def count_all(self) -> int: ...


class RoomRepository(Protocol):
    def get_by_id(self, room_id: int) -> Room | None: ...
    def list_by_owner(self, owner_id: int) -> list[Room]: ...
    def add(self, room: Room) -> Room: ...
    def update(self, room: Room) -> Room: ...
    def delete(self, room_id: int) -> None: ...


class ReviewSessionRepository(Protocol):
    def get_by_id(self, session_id: int) -> ReviewSession | None: ...
    def add(self, session: ReviewSession) -> ReviewSession: ...
    def update(self, session: ReviewSession) -> ReviewSession: ...
    def list_recent_by_user(self, user_id: int, since: datetime) -> list[ReviewSession]: ...


class MnemonicRepository(Protocol):
    def get_by_id(self, mnemonic_id: int) -> MnemonicNote | None: ...
    def list_by_word(self, word_id: int) -> list[MnemonicNote]: ...
    def add(self, note: MnemonicNote) -> MnemonicNote: ...
    def update(self, note: MnemonicNote) -> MnemonicNote: ...


class ReminderRepository(Protocol):
    def get_by_id(self, reminder_id: int) -> Reminder | None: ...
    def list_by_user(self, user_id: int) -> list[Reminder]: ...
    def list_enabled(self) -> list[Reminder]: ...
    def add(self, reminder: Reminder) -> Reminder: ...
    def update(self, reminder: Reminder) -> Reminder: ...
    def delete(self, reminder_id: int) -> None: ...


class RecallSettingsRepository(Protocol):
    def get_by_user(self, user_id: int) -> RecallSettings | None: ...
    def upsert(self, settings: RecallSettings) -> RecallSettings: ...
