import {
  Award,
  Ban,
  Bed,
  BellRing,
  BookOpen,
  Brain,
  BrainCircuit,
  Briefcase,
  Camera,
  Check,
  ChevronDown,
  Circle,
  CircleAlert,
  CircleCheckBig,
  CircleHelp,
  CirclePlay,
  CirclePlus,
  Compass,
  DoorOpen,
  Eye,
  EyeOff,
  FileText,
  FileUp,
  Flame,
  FlaskConical,
  Footprints,
  GraduationCap,
  History,
  Hourglass,
  Info,
  Languages,
  LayoutDashboard,
  Layers,
  Library,
  Lightbulb,
  Link,
  LoaderCircle,
  LogOut,
  Mail,
  Monitor,
  Moon,
  Network,
  PartyPopper,
  Pencil,
  Plane,
  Plus,
  ArrowLeft,
  RotateCw,
  Route,
  Slash,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Sun,
  Tag,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingUp,
  User,
  UtensilsCrossed,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

// Icon names follow the Material Symbols vocabulary this app used before
// migrating to lucide-react, so existing UI copy, room/badge icon values
// persisted by the backend, and call sites didn't need to change.
const ICONS: Record<string, LucideIcon> = {
  add: Plus,
  add_circle: CirclePlus,
  arrow_back: ArrowLeft,
  auto_awesome: Sparkles,
  bed: Bed,
  bedtime: Moon,
  block: Ban,
  bolt: Zap,
  category: Layers,
  celebration: PartyPopper,
  check: Check,
  circle: Circle,
  close: X,
  delete: Trash2,
  desktop_windows: Monitor,
  expand_more: ChevronDown,
  directions_walk: Footprints,
  edit: Pencil,
  error: CircleAlert,
  explore: Compass,
  flight: Plane,
  hourglass_empty: Hourglass,
  hub: Network,
  info: Info,
  label: Tag,
  lightbulb: Lightbulb,
  link: Link,
  local_fire_department: Flame,
  local_library: Library,
  logout: LogOut,
  mail: Mail,
  meeting_room: DoorOpen,
  memory: BrainCircuit,
  menu_book: BookOpen,
  monitoring: TrendingUp,
  notifications_active: BellRing,
  person: User,
  phone_iphone: Smartphone,
  play_circle: CirclePlay,
  progress_activity: LoaderCircle,
  psychology: Brain,
  quiz: CircleHelp,
  refresh: RotateCw,
  restaurant: UtensilsCrossed,
  route: Route,
  school: GraduationCap,
  science: FlaskConical,
  screenshot_monitor: Camera,
  space_dashboard: LayoutDashboard,
  style: Layers,
  task_alt: CircleCheckBig,
  text_snippet: FileText,
  thumb_down: ThumbsDown,
  thumb_up: ThumbsUp,
  timer: Timer,
  translate: Languages,
  tune: SlidersHorizontal,
  update: History,
  upload_file: FileUp,
  visibility: Eye,
  visibility_off: EyeOff,
  wb_sunny: Sun,
  work: Briefcase,
  workspace_premium: Award,
}

export function Icon({ name, className = '' }: { name: string; className?: string }) {
  const Glyph = ICONS[name] ?? Slash
  return <Glyph className={`inline-block h-[1em] w-[1em] shrink-0 align-[-0.125em] ${className}`} aria-hidden="true" />
}
