"""Repository interfaces (ports in the hexagonal-architecture sense).

Application use cases depend on these Protocols, never on concrete
SQLAlchemy classes (Dependency Inversion Principle). Concrete
implementations live in app.infrastructure.repositories and are wired up
in app.api.deps.

Python's structural typing.Protocol is used instead of ABCs so that
implementations don't need to inherit from anything domain-related —
infrastructure stays free to use plain SQLAlchemy-backed classes.
"""
from __future__ import annotations

from datetime import datetime
from typing import Protocol

from app.domain.entities import (
    DesktopNotification,
    Group,
    MnemonicNote,
    RecallSettings,
    DailySessionPreference,
    PracticeExercise,
    WeeklyLearningReport,
    Reminder,
    ReviewSession,
    Room,
    User,
    Word,
)
from app.domain.services.diagnosis_contracts import (
    AcquisitionState,
    Diagnosis,
    InterventionOutcome,
    InterventionPlan,
    LearningObservation,
    ObservationCorrection,
)
from app.domain.services.companion_sessions import CompanionSession, CompanionTurn
from app.domain.services.companion_activities import LearningActivity
from app.domain.services.knowledge_graph import KnowledgeEdge


class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def add(self, user: User) -> User: ...
    def update(self, user: User) -> User: ...
    def delete(self, user_id: int) -> None: ...
    def list_all(self, search: str | None, limit: int, offset: int) -> list[User]: ...
    def count(self) -> int: ...
    def count_registered_since(self, since: datetime) -> int: ...


class GroupRepository(Protocol):
    def get_by_id(self, group_id: int) -> Group | None: ...
    def list_by_owner(self, owner_id: int) -> list[Group]: ...
    def add(self, group: Group) -> Group: ...
    def update(self, group: Group) -> Group: ...
    def delete(self, group_id: int) -> None: ...


class WordRepository(Protocol):
    def get_by_id(self, word_id: int) -> Word | None: ...
    def list_by_group(self, group_id: int) -> list[Word]: ...
    def list_due_for_user(self, user_id: int, limit: int, group_id: int | None = None) -> list[Word]: ...
    def add(self, word: Word) -> Word: ...
    def update(self, word: Word) -> Word: ...
    def delete(self, word_id: int) -> None: ...
    def count_by_group(self, group_id: int) -> int: ...
    def count_mastered_by_group(self, group_id: int) -> int: ...
    def distinct_languages_for_user(self, user_id: int) -> int: ...
    def total_learned_for_owner(self, owner_id: int) -> int: ...
    def count_all(self) -> int: ...


class RoomRepository(Protocol):
    def get_by_id(self, room_id: int) -> Room | None: ...
    def list_by_owner(self, owner_id: int) -> list[Room]: ...
    def add(self, room: Room) -> Room: ...
    def update(self, room: Room) -> Room: ...
    def delete(self, room_id: int) -> None: ...


class ReviewSessionRepository(Protocol):
    def get_by_id(self, session_id: int) -> ReviewSession | None: ...
    def add(self, session: ReviewSession) -> ReviewSession: ...
    def update(self, session: ReviewSession) -> ReviewSession: ...
    def list_recent_by_user(self, user_id: int, since: datetime) -> list[ReviewSession]: ...


class MnemonicRepository(Protocol):
    def get_by_id(self, mnemonic_id: int) -> MnemonicNote | None: ...
    def list_by_word(self, word_id: int) -> list[MnemonicNote]: ...
    def add(self, note: MnemonicNote) -> MnemonicNote: ...
    def update(self, note: MnemonicNote) -> MnemonicNote: ...


class ReminderRepository(Protocol):
    def get_by_id(self, reminder_id: int) -> Reminder | None: ...
    def list_by_user(self, user_id: int) -> list[Reminder]: ...
    def list_enabled(self) -> list[Reminder]: ...
    def add(self, reminder: Reminder) -> Reminder: ...
    def update(self, reminder: Reminder) -> Reminder: ...
    def delete(self, reminder_id: int) -> None: ...


class RecallSettingsRepository(Protocol):
    def get_by_user(self, user_id: int) -> RecallSettings | None: ...
    def upsert(self, settings: RecallSettings) -> RecallSettings: ...


class DailySessionPreferenceRepository(Protocol):
    def get_by_user(self, user_id: int) -> DailySessionPreference | None: ...
    def upsert(self, preference: DailySessionPreference) -> DailySessionPreference: ...


class PracticeExerciseRepository(Protocol):
    def get_by_id(self, exercise_id: int) -> PracticeExercise | None: ...
    def add(self, exercise: PracticeExercise) -> PracticeExercise: ...
    def update(self, exercise: PracticeExercise) -> PracticeExercise: ...


class WeeklyLearningReportRepository(Protocol):
    def get_by_id(self, report_id: int) -> WeeklyLearningReport | None: ...
    def list_by_user(self, user_id: int) -> list[WeeklyLearningReport]: ...
    def add(self, report: WeeklyLearningReport) -> WeeklyLearningReport: ...
    def update(self, report: WeeklyLearningReport) -> WeeklyLearningReport: ...


class DesktopNotificationRepository(Protocol):
    """Outbox of desktop notifications awaiting collection by a shell.

    `list_pending` is scoped by user and bounded by both a row limit and a
    `not_before` cutoff. Neither is optional: an unbounded query would let a
    shell that has been offline for a week collect every reminder it missed
    and fire them as a burst of toasts, which is the storm the caller has to
    be able to prevent.
    """

    def list_pending(
        self, user_id: int, not_before: datetime, limit: int
    ) -> list[DesktopNotification]: ...
    def get_owned(self, user_id: int, notification_id: int) -> DesktopNotification | None: ...
    def dismiss_pending_for_reminder(self, user_id: int, reminder_id: int) -> int: ...
    def list_engagement_history(
        self, user_id: int, since: datetime, limit: int = 500
    ) -> list[DesktopNotification]: ...
    def record_action(self, user_id: int, notification_id: int, action: str) -> str | None: ...
    def add(self, notification: DesktopNotification) -> DesktopNotification: ...
    def mark_delivered(self, user_id: int, notification_ids: list[int]) -> int: ...
    def purge_delivered_before(self, cutoff: datetime) -> int: ...


# AI Learning Diagnosis ports (#180, ADR 0007, issue #181 TODO 2). No
# implementation exists yet — these name the contract #182's persistence
# work and #183/#184's engines are written against, so those phases depend
# on a port rather than deciding their own storage shape ad hoc.


class LearningObservationRepository(Protocol):
    """Append-only: nothing here updates or deletes a recorded observation.
    A wrong observation is corrected by a later, separate one, the same way
    `mistake_memory.py` treats mistake history.

    Query methods below cover the five axes issue #182 TODO 4 names: word,
    pair, time window, modality, and intervention — each account-scoped and
    limit-bounded, so a diagnosis query can never become an unbounded scan
    of one user's entire history. All five exclude an observation once it
    has a correction (issue #229 TODO 5) — the diagnosis engine these feed
    must stop treating a flagged observation as evidence, which is the
    other half of "corrections are new records, not edits": the original
    row survives for audit, but a rebuilt diagnosis no longer sees it.
    """

    def add(self, observation: LearningObservation) -> LearningObservation: ...
    def get_by_id(self, user_id: int, observation_id: str) -> LearningObservation | None: ...
    # #182 TODO 1: the idempotency lookup. A caller checks this before
    # `add`-ing, the same find-before-insert pattern
    # SubmitSyncOperationsUseCase already uses for sync operations.
    def find_by_operation(self, user_id: int, operation_id: str) -> LearningObservation | None: ...
    def list_for_word(self, user_id: int, word_id: int, limit: int = 500) -> list[LearningObservation]: ...
    def list_for_pair(
        self, user_id: int, word_id_a: int, word_id_b: int, limit: int = 500
    ) -> list[LearningObservation]: ...
    def list_in_window(
        self, user_id: int, since: datetime, until: datetime, limit: int = 1000
    ) -> list[LearningObservation]: ...
    def list_by_modality(self, user_id: int, modality: str, limit: int = 500) -> list[LearningObservation]: ...
    def list_by_intervention(
        self, user_id: int, intervention_plan_ref: str, limit: int = 500
    ) -> list[LearningObservation]: ...
    # Issue #229 TODO 5: the private history view. Unlike the five axes
    # above, this deliberately does NOT exclude corrected observations —
    # a learner reviewing their own history needs to see what they already
    # flagged, not have it disappear from view the way it disappears from
    # a diagnosis rebuild's evidence.
    def list_for_user(self, user_id: int, limit: int = 50, offset: int = 0) -> list[LearningObservation]: ...
    # At most one correction per observation (enforced at the storage
    # layer) — flagging is a yes/no fact about a recorded row, not itself
    # a thing worth a history of.
    def add_correction(self, correction: ObservationCorrection) -> ObservationCorrection: ...
    def correction_for(self, user_id: int, observation_id: str) -> ObservationCorrection | None: ...
    def corrections_for(self, user_id: int, observation_ids: list[str]) -> dict[str, ObservationCorrection]: ...


class DiagnosisRepository(Protocol):
    def add(self, diagnosis: Diagnosis) -> Diagnosis: ...
    def latest_for_word(self, user_id: int, word_id: int) -> Diagnosis | None: ...
    def list_for_word(self, user_id: int, word_id: int, limit: int = 50) -> list[Diagnosis]: ...


class InterventionRepository(Protocol):
    def add_plan(self, plan: InterventionPlan) -> InterventionPlan: ...
    def add_outcome(self, outcome: InterventionOutcome) -> InterventionOutcome: ...
    def list_plans_for_word(self, user_id: int, word_id: int) -> list[InterventionPlan]: ...


class CompanionSessionRepository(Protocol):
    def add(self, session: CompanionSession) -> CompanionSession: ...
    def get(self, user_id: int, session_id: str) -> CompanionSession | None: ...
    def update(self, session: CompanionSession) -> CompanionSession: ...
    def list_turns(self, user_id: int, session_id: str, limit: int = 100) -> list[CompanionTurn]: ...
    def add_turn(self, turn: CompanionTurn) -> CompanionTurn: ...
    def find_turn_by_operation(self, user_id: int, session_id: str, operation_id: str) -> CompanionTurn | None: ...
    def delete_content(self, user_id: int, session_id: str) -> None: ...


class CompanionActivityRepository(Protocol):
    def add(self, activity: LearningActivity) -> LearningActivity: ...
    def get(self, user_id: int, session_id: str, activity_id: str) -> LearningActivity | None: ...
    def update(self, activity: LearningActivity) -> LearningActivity: ...
    def find_by_operation(self, user_id: int, session_id: str, operation_id: str) -> LearningActivity | None: ...


class AcquisitionStateRepository(Protocol):
    """Backed by an append-only event table (#184 TODO 2's "immutable
    acquisition events and a derived current state"): `upsert` never
    rewrites a row, it inserts a new transition, and `get_for_word` derives
    "the current state" as the most recent one — the same
    insert-only-then-read-latest shape `DiagnosisRepository` already uses.
    """

    def get_for_word(self, user_id: int, word_id: int) -> AcquisitionState | None: ...
    def upsert(self, state: AcquisitionState) -> AcquisitionState: ...
    def delete_for_word(self, user_id: int, word_id: int) -> None: ...
    # Every word whose current ladder is due at or before `now` and not
    # yet graduated — the dispatch job's and the "due" endpoint's one
    # query, so due-ness is computed identically by both (TODO 2/3).
    # `user_id=None` scans every account (the dispatch job's use); a real
    # id scopes the scan at the query level rather than filtering a
    # globally-limited page afterward, which could hide a busy account's
    # own due words behind another account's on a large, shared table.
    def list_due(self, now, user_id: int | None = None, limit: int = 500) -> list[AcquisitionState]: ...


class KnowledgeEdgeRepository(Protocol):
    """Persisted knowledge-graph edges (issue #138 completion, #203).

    Written on word/mistake mutation, never on read — `replace_for_word`
    is the one write method, and it touches only rows where the given word
    is an endpoint. An edge between two *other* words is never read,
    written, or even considered by a call scoped to a third word.
    """

    def list_all_for_user(self, user_id: int) -> list[KnowledgeEdge]: ...
    def list_related(self, user_id: int, word_id: int, limit: int) -> list[KnowledgeEdge]: ...
    # Atomically replaces every persisted edge touching `word_id` with
    # `edges` — a delete-then-insert scoped to that word, not the account's
    # whole graph, so an edge between two unrelated words never gets a new
    # `updated_at` as a side effect of a third word's edit.
    def replace_for_word(self, user_id: int, word_id: int, edges: list[KnowledgeEdge]) -> None: ...
    def delete_for_word(self, user_id: int, word_id: int) -> None: ...
    # A full-account replace, distinct from replace_for_word: only the
    # one-off backfill (#203 TODO 7) uses this, since it is computing the
    # whole account's graph once anyway and looping replace_for_word per
    # word would mean recomputing that same graph once per word.
    def replace_all_for_user(self, user_id: int, edges: list[KnowledgeEdge]) -> None: ...
